steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
    - --destination=$_IMAGE_NAME:$COMMIT_SHA
    - '--destination=$_IMAGE_NAME:$BRANCH_NAME'
    - --cache=true
    id: Build and Push
  - name: gcr.io/cloud-builders/gke-deploy
    args:
      - prepare
      - '--filename=$_K8S_YAML_PATH'
      - '--image=$_IMAGE_NAME:$COMMIT_SHA'
      - '--app=$_K8S_APP_NAME'
      - '--version=$COMMIT_SHA'
      - '--namespace=$_K8S_NAMESPACE'
      - '--label=$_K8S_LABELS'
      - '--annotation=$_K8S_ANNOTATIONS,gcb-build-id=$BUILD_ID'
      - '--create-application-cr'
      - >-
        --links="Build
        details=https://console.cloud.google.com/cloud-build/builds/$BUILD_ID?project=$PROJECT_ID"
      - '--output=output'
    id: Prepare deploy
  - name: gcr.io/cloud-builders/gsutil
    args:
      - '-c'
      - |-
        if [ "$_OUTPUT_BUCKET_PATH" != "" ]
        then
          gsutil cp -r output/suggested gs://$_OUTPUT_BUCKET_PATH/config/$_K8S_APP_NAME/$BUILD_ID/suggested
          gsutil cp -r output/expanded gs://$_OUTPUT_BUCKET_PATH/config/$_K8S_APP_NAME/$BUILD_ID/expanded
        fi
    id: Save configs
    entrypoint: sh
  - name: gcr.io/cloud-builders/gke-deploy
    args:
      - apply
      - '--filename=output/expanded'
      - '--cluster=$_GKE_CLUSTER'
      - '--location=$_GKE_LOCATION'
      - '--namespace=$_K8S_NAMESPACE'
    id: Apply deploy
images:
  - '$_IMAGE_NAME:$COMMIT_SHA'
substitutions:
  _K8S_ANNOTATIONS: gcb-trigger-id=84cb26fc-7fa0-424d-ab51-df06fdcb1624
  _GKE_CLUSTER: cluster-challenge-mercadolibre
  _K8S_NAMESPACE: core
  _DOCKERFILE_NAME: Dockerfile
  _DOCKERFILE_DIR: ''
  _K8S_APP_NAME: api-shortener-url
  _K8S_YAML_PATH: deployment/
  _OUTPUT_BUCKET_PATH: zeta-treat-365816_cloudbuild/deploy
  _K8S_LABELS: ''
  _GKE_LOCATION: us-central1-c
  _IMAGE_NAME: >-
    gcr.io/zeta-treat-365816/github.com/challenge-mercadolibre-cl/api-shortener-url
tags:
  - gcp-cloud-build-deploy
  - $_K8S_APP_NAME
